dataset:
  type: crossdocked
  file: datasets/processed/crossdocked/per_residue_index.parquet

tokenizer:
  type: pocket_ligand
  max_length: 156
  meta_path: datasets/tokenizer/meta_chembl_db_aa_2_proto4.pkl


output:
  dir: datasets/processed/crossdocked
  file: crossdocked_clean_pocket_selfies_with_tokens.parquet
