experiment:
  name: zinc20_sequence_pretrain
  stage: pretrain

model:
  n_layer: 24
  n_head: 16
  n_embd: 1024
  dropout: 0.1
  bias: false

data:
  loader_type: sequence
  dataset: datasets/processed/zinc20
  block_size: 156
  batch_size: 16
  meta_path: datasets/tokenizer/meta_chembl_db_aa_2_proto4.pkl
  train_bin: datasets/processed/zinc20/train_zinc20.bin
  val_bin: datasets/processed/zinc20/val_zinc20.bin
  pad_token_id: 0

training:
  init_from: scratch
  init_ckpt_path: null
  target_tokens: 524288
  num_gpus: 4
  learning_rate: 6.0e-4
  min_lr: 6.0e-5
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  max_iters: 600000
  lr_decay_iters: 600000
  warmup_iters: 2000
  decay_lr: true

eval:
  eval_interval: 2000
  eval_iters: 200
  eval_only: false
  always_save_checkpoint: false

logging:
  out_dir: checkpoints
  checkpoint_name: ckpt_zinc20.pt
  log_interval: 20

system:
  device: cuda
  dtype: float16
  backend: nccl
  compile: false
